//! Raw FFI declarations for the sensorwatch native C ABI.
//!
//! This is a `-sys` crate: it exposes the flat `extern "C"` `sw_*` functions, the
//! `sw_error_t` / `sw_reading_type_t` enums (as `SW_*` integer constants plus a
//! type alias), the opaque `sw_session` / `sw_snapshot` handle structs, and the
//! `SW_API_VERSION*` constants — exactly as declared in
//! [`include/sensorwatch/sensorwatch.h`](https://github.com/lcjanke2020/sensorwatch/blob/master/include/sensorwatch/sensorwatch.h).
//!
//! The C core is compiled straight into this crate by `build.rs` (with
//! `SW_STATIC`, so `SW_API` is undecorated); there is no separate DLL to load. On
//! non-Windows targets the core still builds and links, and its lifecycle
//! functions return `SW_ERR_UNSUPPORTED_PLATFORM`.
//!
//! Everything here is `unsafe` to call. Prefer the safe, RAII [`sensorwatch`]
//! crate; reach for these raw declarations only for coverage the safe wrapper does
//! not (yet) expose.
//!
//! [`sensorwatch`]: https://docs.rs/sensorwatch
#![no_std]

// `bindings.rs` is generated by bindgen and CHECKED IN (so building this crate
// never needs libclang). Do not edit it by hand: regenerate with
// `regen-bindings.sh` (see that script for the pinned bindgen/libclang versions).
// The CI `bindgen-drift` job re-runs generation and fails if the committed file is
// stale or was hand-edited. The lint allows below are scoped to this module so
// bindgen's C-style names do not leak lint noise into the rest of the crate.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]
mod bindings {
    include!("bindings.rs");
}

pub use bindings::*;
